### ISSUE TITLE
"...1 өвчтөнд 1 код гаргаж өгнө үү" -- gesen anhaaruulgiin design

### ISSUE THREAD

**Issue by amarbayar** [covid-tracing-mongolia/portal#1]
Odoo baigaa project deer: `Тоо, баримт статистикийг үнэн зөв байлгах үүднээс 1 өвчтөнд 1 код гаргаж өгнө үү.` gesen anhaaruulga ni tsenherduu background tai, yag anhaaruulga yum shig medremj turuulehgui text baina. Getel ene ni er ni neleen chuhal zuil uchir anhaaruulgiin temdegtei, anhaaruulj baigaa met ulbar sharduu background (esvel bordertoi box) oruulj irj hunii anhaarliig iluu tatahuits UI uurchlult oruulah heregtei baih. Jishee screenshot dooroos harna uu.

![Screen Shot 2020-11-29 at 2 41 26 PM](https://user-images.githubusercontent.com/8435370/100535146-2639e400-3251-11eb-948c-d453a70f3957.png)

**Comment by tgldr** [comment]
Urd ni warning icon tawiad background ungiig ulaan bolgow.
