### ISSUE TITLE
"Нэг Удаагийн Код үүсгэх" - darhad garch ireh code ni door ni zalgaj bish deerh hesgee darj garch irdeg bolgoh

### ISSUE THREAD

**Issue by amarbayar** [covid-tracing-mongolia/portal#2]
Odoo baigaa ajillagaag uzvel herelegch `Нэг Удаагийн Код үүсгэх` gej darhad neg udaagiin code ni door ni shineer <div> bolon orj irj baigaa. Uuruur helvel `Нэг Удаагийн Код үүсгэх` gesen zaavarchilgaatai heseg ni deeree baigaa baina gesen ug. 

Bidnii zorilgo bol 1 batlagdsan tohioldold 1 shirheg l code gargaj uguh. Tiimees hereglegch negentee `Нэг Удаагийн Код үүсгэх` geed darchihsan bol darhiad darah processiig ni ali boloh boduulahiin tuld daraagiin alham hiih zaig holduulah heregtei. 

Tiimees `Нэг Удаагийн Код үүсгэх` gej daranguut backend ruu huseltee yavuulaad, code oo avna. Code oo gargahdaa odoo baigaa delgetsee darsan baidaltai code oo haruulmaar baina. Tegeed hereglegch `Дараагийн өвчтөнд Нэг Удаагийн Код өгөх` gesen button darj baij dahin eheldeg ch yumuu. 

![Screen Shot 2020-11-29 at 2 46 24 PM](https://user-images.githubusercontent.com/8435370/100535195-aceec100-3251-11eb-80ab-22bbbe19853a.png)

**Comment by tgldr** [comment]
Code uusgeh ued zuwhun dood taliin buyu code haruulj bga heseg garj ireed. Dahin code uusgeh gej darah ued uusgesen code oo hooslood deed hesgiig ni haruulsan.
