### ISSUE TITLE
Neg udaagiin code iig tom bolgoh 

### ISSUE THREAD

**Issue by amarbayar** [covid-tracing-mongolia/portal#3]
Odoo neg udaagiin code gargahad jaahan saaralduu sul ungutei, bas tiim ch tom bish haragdaj baina. Eniig neleen tomosgoh, bas har ungutei bolgovol zugeer baih. Dood taliinh ni ter toonuudiig unshih text nii font size iig bas tom bolgovol zugeer. 

![Screen Shot 2020-11-29 at 2 47 12 PM](https://user-images.githubusercontent.com/8435370/100535217-ea534e80-3251-11eb-9356-23a95b185fa1.png)

Ene task ni gehdee https://github.com/covid-tracing-mongolia/portal/issues/2 toi uyaldah heregtei gedgiig anhaarna uu.

**Comment by tgldr** [comment]
Tomosgood har ungutei bolgoj zassan
